name: 'container-scan-to-sarif-action'
description: 'Converts Container Scan Action output to SARIF'
author: 'Armel Soro'
branding:
  icon: 'check-circle'
  color: 'yellow'
inputs:
  converter-version:
    description: 'Version of the container-scan-to-sarif tool. See https://github.com/rm3l/container-scan-to-sarif/releases'
    required: false
    default: '0.5.0'
  input-file:
    description: 'Path to the input Container Scan report to convert'
    required: true
  output-file:
    description: 'Path to the output SARIF report to generate'
    required: false
    default: 'scanreport.sarif'
outputs:
  sarif-report-path:
    description: 'Path to the SARIF report generated'
    value: ${{ steps.scan-to-sarif.outputs.sarif-report-path }}
runs:
  using: "composite"
  steps:
    - id: container-scan-to-sarif-downloader
      run: |
        mkdir -p ~/.local/bin
        curl -L "https://github.com/rm3l/container-scan-to-sarif/releases/download/${{ inputs.converter-version }}/container-scan-to-sarif_${{ inputs.converter-version }}_Linux_x86_64.tar.gz" \
          | tar zx -C ~/.local/bin --strip-components=1
        chmod +x ~/.local/bin/container-scan-to-sarif
      shell: bash
    - id: scan-to-sarif
      run: |
        ~/.local/bin/container-scan-to-sarif \
          -input "${{ inputs.input-file }}" \
          -output "${{ inputs.output-file }}"
        echo "::set-output name=sarif-report-path::${{ inputs.output-file }}"
      shell: bash
