on: [push]

jobs:
  container-scan-to-sarif_job:
    runs-on: ubuntu-latest
    name: A job to convert Container Scan reports to SARIF
    steps:
      - uses: actions/checkout@v2

      - name: Scan sample image with Azure Container Scan
        id: container-image-scan
        continue-on-error: true
        uses: Azure/container-scan@v0.1
        with:
          image-name: debian:11

      - name: Convert Container Scan Output to SARIF
        id: container-scan-to-sarif
        if: ${{ always() }}
        uses: ./
        with:
          converter-version: 0.2.2
          input-file: ${{ steps.container-image-scan.outputs.scan-report-path }}

      - name: Upload SARIF reports to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: ${{ steps.container-scan-to-sarif.outputs.sarif-report-path }}
